2022-02-25 17:15:42,222 INFO    Thread-43 :700322 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-25 17:15:42,222 INFO    Thread-43 :700322 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-25 17:15:42,222 INFO    Thread-43 :700322 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'run_id': 'yk2pvfyd', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-mvcqeh0x/config-yk2pvfyd.yaml', 'sweep_id': 'mvcqeh0x'}
2022-02-25 17:15:42,223 INFO    Thread-43 :700322 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-25 17:15:42,223 INFO    Thread-43 :700322 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/logs/debug.log
2022-02-25 17:15:42,223 INFO    Thread-43 :700322 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/logs/debug-internal.log
2022-02-25 17:15:42,224 INFO    Thread-43 :700322 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e145cf8e0>
2022-02-25 17:15:42,224 INFO    Thread-43 :700322 [wandb_init.py:init():420] calling init triggers
2022-02-25 17:15:42,224 INFO    Thread-43 :700322 [wandb_init.py:init():425] wandb.init called with sweep_config: {'batch_size': 64, 'num_hidden_neurons': 256, 'num_layers': 3, 'weight_decay': 0.0015}
config: {'epochs': 10, 'num_layers': 3, 'num_hidden_neurons': 128, 'weight_decay': 0.0005, 'learning_rate': 0.0005, 'optimizer': 'Nadam', 'batch_size': 64, 'activation': 'ReLU', 'initializer': 'xavier'}
2022-02-25 17:15:42,225 INFO    Thread-43 :700322 [wandb_init.py:init():471] starting backend
2022-02-25 17:15:42,225 INFO    Thread-43 :700322 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-25 17:15:42,228 INFO    Thread-43 :700322 [backend.py:ensure_launched():219] starting backend process...
2022-02-25 17:15:42,247 INFO    Thread-43 :700322 [backend.py:ensure_launched():224] started backend process with pid: 706021
2022-02-25 17:15:42,250 INFO    Thread-43 :700322 [wandb_init.py:init():480] backend started and connected
2022-02-25 17:15:42,270 INFO    Thread-43 :700322 [wandb_run.py:_config_callback():966] config_cb None None {'batch_size': 64, 'num_hidden_neurons': 256, 'num_layers': 3, 'weight_decay': 0.0015}
2022-02-25 17:15:42,273 INFO    Thread-43 :700322 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-25 17:15:42,274 INFO    Thread-43 :700322 [wandb_init.py:init():550] updated telemetry
2022-02-25 17:15:42,295 INFO    Thread-43 :700322 [wandb_init.py:init():581] communicating current version
2022-02-25 17:15:42,946 INFO    Thread-43 :700322 [wandb_init.py:init():586] got version response 
2022-02-25 17:15:42,946 INFO    Thread-43 :700322 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-25 17:15:43,256 INFO    Thread-43 :700322 [wandb_init.py:init():624] starting run threads in backend
2022-02-25 17:15:48,136 INFO    Thread-43 :700322 [wandb_run.py:_console_start():1827] atexit reg
2022-02-25 17:15:48,137 INFO    Thread-43 :700322 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-25 17:15:48,137 INFO    Thread-43 :700322 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-25 17:15:48,138 INFO    Thread-43 :700322 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-25 17:15:48,138 INFO    Thread-43 :700322 [wandb_init.py:init():651] run started, returning control to user process
2022-02-25 17:17:02,904 ERROR   Thread-33 :700322 [internal_api.py:agent_heartbeat():1743] Error communicating with W&B: context deadline exceeded
2022-02-25 17:17:05,505 INFO    Thread-43 :700322 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/yk2pvfyd
2022-02-25 17:17:05,506 INFO    Thread-43 :700322 [jupyter.py:save_history():429] not saving jupyter history
2022-02-25 17:17:05,506 INFO    Thread-43 :700322 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-25 17:17:05,506 INFO    Thread-43 :700322 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-25 17:17:05,506 INFO    Thread-43 :700322 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-25 17:17:05,508 INFO    Thread-43 :700322 [wandb_run.py:_restore():1769] restore
2022-02-25 17:17:08,332 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:08,334 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:09,799 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:09,799 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:10,736 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:13,924 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:13,925 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:13,925 ERROR   Thread-33 :700322 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 146, in execute
    six.reraise(*sys.exc_info())
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-02-25 17:17:15,837 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:20,938 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:26,039 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:31,140 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:36,242 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:41,342 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:42,063 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:42,064 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:43,504 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:43,505 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:46,443 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:51,544 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:17:56,645 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:01,746 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:06,847 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:11,948 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:17,050 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:22,151 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:27,252 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:32,353 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:37,454 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:42,556 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:47,657 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:52,758 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:18:57,859 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:02,960 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:08,061 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:13,162 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:16,261 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:16,262 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"errors":[{"message":"Error 1040: Too many connections","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
2022-02-25 17:19:18,263 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:19,255 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:19,256 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:21,996 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:21,997 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:21,997 ERROR   Thread-33 :700322 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 146, in execute
    six.reraise(*sys.exc_info())
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-02-25 17:19:23,364 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:26,676 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:26,677 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:28,465 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:33,567 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:34,993 ERROR   Thread-33 :700322 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:34,994 ERROR   Thread-33 :700322 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:38,668 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:43,769 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:48,870 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:53,971 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:19:59,072 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:20:04,173 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:20:09,274 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:20:14,375 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:20:19,476 INFO    Thread-43 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-25 17:20:24,577 INFO    Thread-43 :700322 [wandb_run.py:_restore():1769] restore
2022-02-25 17:20:26,961 INFO    MainThread:700322 [pyagent.py:run():318] Starting sweep agent: entity=None, project=None, count=20
2022-02-25 17:20:28,354 INFO    Thread-53 :700322 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-25 17:20:28,354 INFO    Thread-53 :700322 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-25 17:20:28,355 INFO    Thread-53 :700322 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'run_id': 'orxzazmk', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-mvcqeh0x/config-orxzazmk.yaml', 'sweep_id': 'mvcqeh0x'}
2022-02-25 17:20:28,355 INFO    Thread-53 :700322 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-25 17:20:28,355 INFO    Thread-53 :700322 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172028-orxzazmk/logs/debug.log
2022-02-25 17:20:28,356 INFO    Thread-53 :700322 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172028-orxzazmk/logs/debug-internal.log
2022-02-25 17:20:28,356 INFO    Thread-53 :700322 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e14802490>
2022-02-25 17:20:28,357 INFO    Thread-53 :700322 [wandb_init.py:init():420] calling init triggers
2022-02-25 17:20:28,358 INFO    Thread-53 :700322 [wandb_init.py:init():425] wandb.init called with sweep_config: {'batch_size': 64, 'num_hidden_neurons': 32, 'num_layers': 3, 'weight_decay': 0}
config: {'epochs': 10, 'num_layers': 3, 'num_hidden_neurons': 128, 'weight_decay': 0.0005, 'learning_rate': 0.0005, 'optimizer': 'Nadam', 'batch_size': 64, 'activation': 'ReLU', 'initializer': 'xavier'}
2022-02-25 17:20:28,358 INFO    Thread-53 :700322 [wandb_init.py:init():471] starting backend
2022-02-25 17:20:28,359 INFO    Thread-53 :700322 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-25 17:20:28,362 INFO    Thread-53 :700322 [backend.py:ensure_launched():219] starting backend process...
2022-02-25 17:20:28,385 INFO    Thread-53 :700322 [backend.py:ensure_launched():224] started backend process with pid: 706380
2022-02-25 17:20:28,387 INFO    Thread-53 :700322 [wandb_init.py:init():480] backend started and connected
2022-02-25 17:20:28,407 INFO    Thread-53 :700322 [wandb_run.py:_config_callback():966] config_cb None None {'batch_size': 64, 'num_hidden_neurons': 32, 'num_layers': 3, 'weight_decay': 0}
2022-02-25 17:20:28,411 INFO    Thread-53 :700322 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-25 17:20:28,411 INFO    Thread-53 :700322 [wandb_init.py:init():550] updated telemetry
2022-02-25 17:20:28,433 INFO    Thread-53 :700322 [wandb_init.py:init():581] communicating current version
2022-02-25 17:20:29,059 INFO    Thread-53 :700322 [wandb_init.py:init():586] got version response 
2022-02-25 17:20:29,059 INFO    Thread-53 :700322 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-25 17:20:29,344 INFO    Thread-53 :700322 [wandb_init.py:init():624] starting run threads in backend
2022-02-25 17:20:34,349 INFO    Thread-53 :700322 [wandb_run.py:_console_start():1827] atexit reg
2022-02-25 17:20:34,350 INFO    Thread-53 :700322 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-25 17:20:34,350 INFO    Thread-53 :700322 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-25 17:20:34,350 INFO    Thread-53 :700322 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-25 17:20:34,351 INFO    Thread-53 :700322 [wandb_init.py:init():651] run started, returning control to user process
2022-02-25 17:20:52,486 INFO    Thread-53 :700322 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/orxzazmk
2022-02-25 17:20:52,487 INFO    Thread-53 :700322 [jupyter.py:save_history():429] not saving jupyter history
2022-02-25 17:20:52,487 INFO    Thread-53 :700322 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-25 17:20:52,487 INFO    Thread-53 :700322 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-25 17:20:52,488 INFO    Thread-53 :700322 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-25 17:20:52,491 INFO    Thread-53 :700322 [wandb_run.py:_restore():1769] restore
2022-02-25 17:20:53,373 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-02-25 17:20:53,671 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-02-25 17:20:54,362 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22439
}

2022-02-25 17:20:54,465 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22439
}

2022-02-25 17:20:54,566 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22439
}

2022-02-25 17:20:54,668 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22439
}

2022-02-25 17:20:54,769 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22439
}

2022-02-25 17:20:54,870 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:54,973 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:55,076 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:55,177 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:55,279 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:55,382 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:55,486 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:56,017 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}

2022-02-25 17:20:56,677 INFO    Thread-53 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22439
  total_bytes: 22439
}
local_info {
}

2022-02-25 17:20:58,116 INFO    Thread-53 :700322 [wandb_run.py:_append_history():2144] rendering history
2022-02-25 17:20:58,117 INFO    Thread-53 :700322 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-25 17:20:58,117 INFO    Thread-53 :700322 [wandb_run.py:_append_files():2194] logging synced files
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'run_id': 'krsc8j8s', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-mvcqeh0x/config-krsc8j8s.yaml', 'sweep_id': 'mvcqeh0x'}
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172100-krsc8j8s/logs/debug.log
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172100-krsc8j8s/logs/debug-internal.log
2022-02-25 17:21:00,026 INFO    Thread-62 :700322 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e14734f70>
2022-02-25 17:21:00,027 INFO    Thread-62 :700322 [wandb_init.py:init():420] calling init triggers
2022-02-25 17:21:00,027 INFO    Thread-62 :700322 [wandb_init.py:init():425] wandb.init called with sweep_config: {'batch_size': 64, 'num_hidden_neurons': 32, 'num_layers': 5, 'weight_decay': 0.0005}
config: {'epochs': 10, 'num_layers': 3, 'num_hidden_neurons': 128, 'weight_decay': 0.0005, 'learning_rate': 0.0005, 'optimizer': 'Nadam', 'batch_size': 64, 'activation': 'ReLU', 'initializer': 'xavier'}
2022-02-25 17:21:00,027 INFO    Thread-62 :700322 [wandb_init.py:init():471] starting backend
2022-02-25 17:21:00,027 INFO    Thread-62 :700322 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-25 17:21:00,028 INFO    Thread-62 :700322 [backend.py:ensure_launched():219] starting backend process...
2022-02-25 17:21:00,039 INFO    Thread-62 :700322 [backend.py:ensure_launched():224] started backend process with pid: 706468
2022-02-25 17:21:00,040 INFO    Thread-62 :700322 [wandb_init.py:init():480] backend started and connected
2022-02-25 17:21:00,055 INFO    Thread-62 :700322 [wandb_run.py:_config_callback():966] config_cb None None {'batch_size': 64, 'num_hidden_neurons': 32, 'num_layers': 5, 'weight_decay': 0.0005}
2022-02-25 17:21:00,058 INFO    Thread-62 :700322 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-25 17:21:00,059 INFO    Thread-62 :700322 [wandb_init.py:init():550] updated telemetry
2022-02-25 17:21:00,086 INFO    Thread-62 :700322 [wandb_init.py:init():581] communicating current version
2022-02-25 17:21:00,881 INFO    Thread-62 :700322 [wandb_init.py:init():586] got version response 
2022-02-25 17:21:00,882 INFO    Thread-62 :700322 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-25 17:21:01,195 INFO    Thread-62 :700322 [wandb_init.py:init():624] starting run threads in backend
2022-02-25 17:21:06,137 INFO    Thread-62 :700322 [wandb_run.py:_console_start():1827] atexit reg
2022-02-25 17:21:06,137 INFO    Thread-62 :700322 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-25 17:21:06,138 INFO    Thread-62 :700322 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-25 17:21:06,138 INFO    Thread-62 :700322 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-25 17:21:06,139 INFO    Thread-62 :700322 [wandb_init.py:init():651] run started, returning control to user process
2022-02-25 17:21:28,810 INFO    Thread-62 :700322 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/krsc8j8s
2022-02-25 17:21:28,811 INFO    Thread-62 :700322 [jupyter.py:save_history():429] not saving jupyter history
2022-02-25 17:21:28,811 INFO    Thread-62 :700322 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-25 17:21:28,811 INFO    Thread-62 :700322 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-25 17:21:28,811 INFO    Thread-62 :700322 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-25 17:21:28,814 INFO    Thread-62 :700322 [wandb_run.py:_restore():1769] restore
2022-02-25 17:21:29,174 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-02-25 17:21:29,575 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-02-25 17:21:30,228 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22447
}

2022-02-25 17:21:30,331 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22447
}

2022-02-25 17:21:30,434 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22447
}

2022-02-25 17:21:30,559 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22447
}

2022-02-25 17:21:30,661 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 22447
}

2022-02-25 17:21:30,765 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:30,870 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:30,973 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,076 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,180 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,283 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,387 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,491 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:31,987 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}

2022-02-25 17:21:32,622 INFO    Thread-62 :700322 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 22447
  total_bytes: 22447
}
local_info {
}

2022-02-25 17:21:34,005 INFO    Thread-62 :700322 [wandb_run.py:_append_history():2144] rendering history
2022-02-25 17:21:34,006 INFO    Thread-62 :700322 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-25 17:21:34,006 INFO    Thread-62 :700322 [wandb_run.py:_append_files():2194] logging synced files
2022-02-25 17:21:37,170 INFO    Thread-71 :700322 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-25 17:21:37,170 INFO    Thread-71 :700322 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-25 17:21:37,170 INFO    Thread-71 :700322 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'run_id': 't4fczhsz', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-mvcqeh0x/config-t4fczhsz.yaml', 'sweep_id': 'mvcqeh0x'}
2022-02-25 17:21:37,171 INFO    Thread-71 :700322 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-25 17:21:37,171 INFO    Thread-71 :700322 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172137-t4fczhsz/logs/debug.log
2022-02-25 17:21:37,172 INFO    Thread-71 :700322 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_172137-t4fczhsz/logs/debug-internal.log
2022-02-25 17:21:37,172 INFO    Thread-71 :700322 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e1471b100>
2022-02-25 17:21:37,173 INFO    Thread-71 :700322 [wandb_init.py:init():420] calling init triggers
2022-02-25 17:21:37,173 INFO    Thread-71 :700322 [wandb_init.py:init():425] wandb.init called with sweep_config: {'batch_size': 32, 'num_hidden_neurons': 64, 'num_layers': 5, 'weight_decay': 0.001}
config: {'epochs': 10, 'num_layers': 3, 'num_hidden_neurons': 128, 'weight_decay': 0.0005, 'learning_rate': 0.0005, 'optimizer': 'Nadam', 'batch_size': 64, 'activation': 'ReLU', 'initializer': 'xavier'}
2022-02-25 17:21:37,173 INFO    Thread-71 :700322 [wandb_init.py:init():471] starting backend
2022-02-25 17:21:37,173 INFO    Thread-71 :700322 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-25 17:21:37,177 INFO    Thread-71 :700322 [backend.py:ensure_launched():219] starting backend process...
2022-02-25 17:21:37,201 INFO    Thread-71 :700322 [backend.py:ensure_launched():224] started backend process with pid: 706511
2022-02-25 17:21:37,204 INFO    Thread-71 :700322 [wandb_init.py:init():480] backend started and connected
2022-02-25 17:21:37,225 INFO    Thread-71 :700322 [wandb_run.py:_config_callback():966] config_cb None None {'batch_size': 32, 'num_hidden_neurons': 64, 'num_layers': 5, 'weight_decay': 0.001}
2022-02-25 17:21:37,229 INFO    Thread-71 :700322 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-25 17:21:37,229 INFO    Thread-71 :700322 [wandb_init.py:init():550] updated telemetry
2022-02-25 17:21:37,255 INFO    Thread-71 :700322 [wandb_init.py:init():581] communicating current version
2022-02-25 17:21:37,913 INFO    Thread-71 :700322 [wandb_init.py:init():586] got version response 
2022-02-25 17:21:37,914 INFO    Thread-71 :700322 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-25 17:21:38,217 INFO    Thread-71 :700322 [wandb_init.py:init():624] starting run threads in backend
2022-02-25 17:21:43,155 INFO    Thread-71 :700322 [wandb_run.py:_console_start():1827] atexit reg
2022-02-25 17:21:43,156 INFO    Thread-71 :700322 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-25 17:21:43,156 INFO    Thread-71 :700322 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-25 17:21:43,157 INFO    Thread-71 :700322 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-25 17:21:43,157 INFO    Thread-71 :700322 [wandb_init.py:init():651] run started, returning control to user process
2022-02-25 17:22:10,799 ERROR   Thread-43 :700322 [wandb_run.py:_atexit_cleanup():1815] Problem finishing run
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1988, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1928, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
Exception
