2022-02-24 16:06:39,943 INFO    MainThread:534558 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-24 16:06:39,943 INFO    MainThread:534558 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-24 16:06:39,943 INFO    MainThread:534558 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'silent': 'true', 'run_id': '1u0byzwb', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-d840rglg/config-1u0byzwb.yaml', 'sweep_id': 'd840rglg'}
2022-02-24 16:06:39,943 INFO    MainThread:534558 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-24 16:06:39,944 ERROR   MainThread:534558 [wandb_setup.py:_flush():75] [34m[1mwandb[0m: [32m[41mERROR[0m Run 1u0byzwb errored: ValueError('operands could not be broadcast together with shapes (6000,10) (6000,) ')
2022-02-24 16:06:39,944 ERROR   MainThread:534558 [wandb_setup.py:_flush():75] [34m[1mwandb[0m: [32m[41mERROR[0m Detected 3 failed runs in the first 60 seconds, killing sweep.
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_setup.py:_flush():75] [34m[1mwandb[0m: To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2022-02-24 16:06:39,944 WARNING MainThread:534558 [wandb_setup.py:_flush():75] [34m[1mwandb[0m: [33mWARNING[0m Ignored wandb.init() arg project when running a sweep.
2022-02-24 16:06:39,944 WARNING MainThread:534558 [wandb_setup.py:_flush():75] [34m[1mwandb[0m: [33mWARNING[0m Ignored wandb.init() arg entity when running a sweep.
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160639-1u0byzwb/logs/debug.log
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160639-1u0byzwb/logs/debug-internal.log
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_init.py:init():420] calling init triggers
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_init.py:init():425] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 16, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 32, 'num_layers': 3, 'optimizer': 'Adam', 'weight_decay': 0}
config: {}
2022-02-24 16:06:39,944 INFO    MainThread:534558 [wandb_init.py:init():471] starting backend
2022-02-24 16:06:39,945 INFO    MainThread:534558 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-24 16:06:39,948 INFO    MainThread:534558 [backend.py:ensure_launched():219] starting backend process...
2022-02-24 16:06:39,958 INFO    MainThread:534558 [backend.py:ensure_launched():224] started backend process with pid: 538817
2022-02-24 16:06:39,959 INFO    MainThread:534558 [wandb_init.py:init():480] backend started and connected
2022-02-24 16:06:39,971 INFO    MainThread:534558 [wandb_run.py:_config_callback():966] config_cb None None {'activation': 'ReLU', 'batch_size': 16, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 32, 'num_layers': 3, 'optimizer': 'Adam', 'weight_decay': 0}
2022-02-24 16:06:39,974 INFO    MainThread:534558 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-24 16:06:39,975 INFO    MainThread:534558 [wandb_init.py:init():550] updated telemetry
2022-02-24 16:06:39,997 INFO    MainThread:534558 [wandb_init.py:init():581] communicating current version
2022-02-24 16:06:40,663 INFO    MainThread:534558 [wandb_init.py:init():586] got version response 
2022-02-24 16:06:40,663 INFO    MainThread:534558 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-24 16:06:40,956 INFO    MainThread:534558 [wandb_init.py:init():624] starting run threads in backend
2022-02-24 16:06:45,895 INFO    MainThread:534558 [wandb_run.py:_console_start():1827] atexit reg
2022-02-24 16:06:45,896 INFO    MainThread:534558 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-24 16:06:45,896 INFO    MainThread:534558 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-24 16:06:45,897 INFO    MainThread:534558 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-24 16:06:45,897 INFO    MainThread:534558 [wandb_init.py:init():651] run started, returning control to user process
2022-02-24 16:06:46,422 INFO    MainThread:534558 [pyagent.py:run():318] Starting sweep agent: entity=None, project=None, count=10
2022-02-24 16:06:47,861 INFO    Thread-199:534558 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-24 16:06:47,862 INFO    Thread-199:534558 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-24 16:06:47,862 INFO    Thread-199:534558 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'silent': 'true', 'sweep_id': 'fd0c0zla', 'run_id': '3nfxxv68', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-fd0c0zla/config-3nfxxv68.yaml'}
2022-02-24 16:06:47,863 INFO    Thread-199:534558 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-24 16:06:47,863 INFO    Thread-199:534558 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160647-3nfxxv68/logs/debug.log
2022-02-24 16:06:47,864 INFO    Thread-199:534558 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160647-3nfxxv68/logs/debug-internal.log
2022-02-24 16:06:47,864 INFO    Thread-199:534558 [wandb_init.py:init():420] calling init triggers
2022-02-24 16:06:47,864 INFO    Thread-199:534558 [wandb_init.py:init():425] wandb.init called with sweep_config: {'activation': 'Sigmoid', 'batch_size': 32, 'epochs': 5, 'initializer': 'xavier', 'learning_rate': 0.0001, 'num_hidden_neurons': 32, 'num_layers': 4, 'optimizer': 'RMSprop', 'weight_decay': 0}
config: {'epochs': 5, 'num_hidden_layers': 3, 'num_hidden_neurons': 32, 'weight_decay': 0, 'learning_rate': 0.001, 'optimizer': 'SGD', 'batch_size': 16, 'activation': 'Tanh', 'initializer': 'xavier', 'loss': 'CategoricalCrossEntropy'}
2022-02-24 16:06:47,864 INFO    Thread-199:534558 [wandb_init.py:init():471] starting backend
2022-02-24 16:06:47,864 INFO    Thread-199:534558 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-24 16:06:47,865 INFO    Thread-199:534558 [backend.py:ensure_launched():219] starting backend process...
2022-02-24 16:06:47,874 INFO    Thread-199:534558 [backend.py:ensure_launched():224] started backend process with pid: 538911
2022-02-24 16:06:47,875 INFO    Thread-199:534558 [wandb_init.py:init():480] backend started and connected
2022-02-24 16:06:47,887 INFO    Thread-199:534558 [wandb_run.py:_config_callback():966] config_cb None None {'activation': 'Sigmoid', 'batch_size': 32, 'epochs': 5, 'initializer': 'xavier', 'learning_rate': 0.0001, 'num_hidden_neurons': 32, 'num_layers': 4, 'optimizer': 'RMSprop', 'weight_decay': 0}
2022-02-24 16:06:47,890 INFO    Thread-199:534558 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-24 16:06:47,891 INFO    Thread-199:534558 [wandb_init.py:init():550] updated telemetry
2022-02-24 16:06:47,914 INFO    Thread-199:534558 [wandb_init.py:init():581] communicating current version
2022-02-24 16:06:48,545 INFO    Thread-199:534558 [wandb_init.py:init():586] got version response 
2022-02-24 16:06:48,546 INFO    Thread-199:534558 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-24 16:06:48,853 INFO    Thread-199:534558 [wandb_init.py:init():624] starting run threads in backend
2022-02-24 16:06:53,855 INFO    Thread-199:534558 [wandb_run.py:_console_start():1827] atexit reg
2022-02-24 16:06:53,855 INFO    Thread-199:534558 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-24 16:06:53,855 INFO    Thread-199:534558 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-24 16:06:53,911 INFO    Thread-199:534558 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-24 16:06:53,911 INFO    Thread-199:534558 [wandb_init.py:init():651] run started, returning control to user process
2022-02-24 16:06:56,065 INFO    Thread-199:534558 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/3nfxxv68
2022-02-24 16:06:56,065 INFO    Thread-199:534558 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-24 16:06:56,067 INFO    Thread-199:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:06:56,921 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:06:57,312 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:06:57,865 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21329
}

2022-02-24 16:06:57,969 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21329
}

2022-02-24 16:06:58,074 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21329
}

2022-02-24 16:06:58,178 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21329
}

2022-02-24 16:06:58,282 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21329
}

2022-02-24 16:06:58,386 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:58,493 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:58,597 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:58,701 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:58,805 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:58,909 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:59,011 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:06:59,628 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}

2022-02-24 16:07:00,294 INFO    Thread-199:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21329
  total_bytes: 21329
}
local_info {
}

2022-02-24 16:07:01,672 ERROR   MainThread:534558 [pyagent.py:_run_jobs_from_queue():230] Run 3nfxxv68 errored: ValueError('operands could not be broadcast together with shapes (6000,10) (6000,) ')
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'silent': 'true', 'run_id': 'le4k3sgr', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-fd0c0zla/config-le4k3sgr.yaml', 'sweep_id': 'fd0c0zla'}
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160704-le4k3sgr/logs/debug.log
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160704-le4k3sgr/logs/debug-internal.log
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:init():420] calling init triggers
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:init():425] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 64, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 64, 'num_layers': 3, 'optimizer': 'SGD', 'weight_decay': 0.5}
config: {'epochs': 5, 'num_hidden_layers': 3, 'num_hidden_neurons': 32, 'weight_decay': 0, 'learning_rate': 0.001, 'optimizer': 'SGD', 'batch_size': 16, 'activation': 'Tanh', 'initializer': 'xavier', 'loss': 'CategoricalCrossEntropy'}
2022-02-24 16:07:04,191 INFO    Thread-208:534558 [wandb_init.py:init():471] starting backend
2022-02-24 16:07:04,191 INFO    Thread-208:534558 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-24 16:07:04,192 INFO    Thread-208:534558 [backend.py:ensure_launched():219] starting backend process...
2022-02-24 16:07:04,207 INFO    Thread-208:534558 [backend.py:ensure_launched():224] started backend process with pid: 539057
2022-02-24 16:07:04,210 INFO    Thread-208:534558 [wandb_init.py:init():480] backend started and connected
2022-02-24 16:07:04,223 INFO    Thread-208:534558 [wandb_run.py:_config_callback():966] config_cb None None {'activation': 'ReLU', 'batch_size': 64, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 64, 'num_layers': 3, 'optimizer': 'SGD', 'weight_decay': 0.5}
2022-02-24 16:07:04,226 INFO    Thread-208:534558 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-24 16:07:04,227 INFO    Thread-208:534558 [wandb_init.py:init():550] updated telemetry
2022-02-24 16:07:04,249 INFO    Thread-208:534558 [wandb_init.py:init():581] communicating current version
2022-02-24 16:07:04,869 INFO    Thread-208:534558 [wandb_init.py:init():586] got version response 
2022-02-24 16:07:04,869 INFO    Thread-208:534558 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-24 16:07:05,194 INFO    Thread-208:534558 [wandb_init.py:init():624] starting run threads in backend
2022-02-24 16:07:09,880 INFO    Thread-208:534558 [wandb_run.py:_console_start():1827] atexit reg
2022-02-24 16:07:09,880 INFO    Thread-208:534558 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_init.py:init():651] run started, returning control to user process
2022-02-24 16:07:11,103 INFO    Thread-208:534558 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/le4k3sgr
2022-02-24 16:07:11,103 INFO    Thread-208:534558 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-24 16:07:11,106 INFO    Thread-208:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:07:11,389 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:07:11,738 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:07:12,222 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 7309
}

2022-02-24 16:07:12,328 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,433 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,542 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,646 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,750 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:12,856 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:12,960 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,064 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,168 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,272 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,376 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,484 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:14,433 INFO    Thread-208:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:07:15,796 ERROR   Thread-208:534558 [wandb_run.py:_atexit_cleanup():1815] Problem finishing run
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 302, in _run_job
    self._function()
  File "/tmp/ipykernel_534558/553927813.py", line 55, in sweep
    model.train(X, y_train_one_hot, validation_data=(X_val, y_val),
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Model.py", line 114, in train
    self.validate(X_val, Y_val)
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Model.py", line 134, in validate
    batch_loss = self.loss.forward(output, batch_Y)
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Loss/CategoricalCrossEntropy.py", line 15, in forward
    return np.sum(log_likelihood * y_true, axis=1)
ValueError: operands could not be broadcast together with shapes (6000,10) (6000,) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1988, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1928, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-02-24 16:07:15,799 INFO    MainThread:534558 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-24 16:07:15,799 INFO    MainThread:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:07:15,803 INFO    MainThread:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:07:16,174 INFO    MainThread:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

